export const ACTIONS = {
  APPEND_ACTIVITY: 'APPEND_ACTIVITY',
  DISCARD_ACTIVITY: 'DISCARD_ACTIVITY',
  HYDRATE_ACTIVITIES: 'HYDRATE_ACTIVITIES',
  STORE_ADVICE: 'STORE_ADVICE',
  MARK_ACTION_DONE: 'MARK_ACTION_DONE',
  UNMARK_ACTION_DONE: 'UNMARK_ACTION_DONE',
  SHIFT_VIEWPORT: 'SHIFT_VIEWPORT',
  SIGNAL_LOADING: 'SIGNAL_LOADING',
  SIGNAL_READY: 'SIGNAL_READY',
  SIGNAL_FAULT: 'SIGNAL_FAULT',
  CLEAR_FAULT: 'CLEAR_FAULT',
};
